spring:
  application:
    name: settlement-service
  config:
    import:
      - classpath:eventTopic.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/settlement
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 0
  shutdown: graceful

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

encrypter:
  secret-key: "IQDVvuZqN2ulwDf2qcPJ/J9kJqxkxhKApAvLf2bh3zw="

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:eventTopic.yaml
      - "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:mysql://mysql:3306/settlement
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
    kafka:
      text-bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
      consumer:
        group-id: settlement-service
server:
  port: 8080
  shutdown: graceful
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
