spring:
  application:
    name: settlement-service
  config:
    import:
      - classpath:eventTopic.yaml
      - classpath:taxRate.yaml
  mail:
    password: ${MAIL_PASSWORD}
    username: kr.promptoven@gmail.com
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
mailing:
  admin-and-investor:
    - "astar5327z@gmail.com"
    - "jaehunlee526@gmail.com"
    - "yuseok.kim@edushare.kr"
    - "singyu13@gmail.com"
    - "jangdebug@gmail.com"
    - "osb4469@gmail.com"
    - "qjsduddl12@gmail.com"
    - "hitkey0925@gmail.com"
encrypter:
  secret-key: "IQDVvuZqN2ulwDf2qcPJ/J9kJqxkxhKApAvLf2bh3zw="

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:eventTopic.yaml
      - classpath:taxRate.yaml
      - "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:mysql://mysql:3306/settlement
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  cloud:
    config:
      fail-fast: false
      name: settlement-service,eventTopic,taxRate
  kafka:
    text-bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    consumer:
      group-id: settlement-service
server:
  port: 8080
  shutdown: graceful
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:eventTopic.yaml
      - classpath:taxRate.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/settlement
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      enabled: false
server:
  port: 0
  shutdown: graceful

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}